version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: mmuser_password
      POSTGRES_DB: mattermost
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: mattermost/mattermost-team-edition:latest
    restart: always
    ports:
      - "8065:8065"
    environment:
      MM_CONFIG: /mattermost/config/config.json
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10
    volumes:
      - app_data:/mattermost/data
      - ./config:/mattermost/config
    depends_on:
      - db

volumes:
  db_data:
  app_data:
